version: '3.5'

services:
  traefik-letsencrypt:
    image: jairsjunior/traefik-letsencrypt:local
    build: .
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      - HTTPS_REDIRECT=true