version: '3.5'

services:
  traefik-letsencrypt-alpine-httpchallenge:
    image: tiagostutz/traefik-letsencrypt:1.6-alpine-httpchallenge
    build: .
  traefik-letsencrypt-httpchallenge:
    image: tiagostutz/traefik-letsencrypt:1.6-httpchallenge
    build: .
  traefik-letsencrypt:
    image: tiagostutz/traefik-letsencrypt:1.6
    build: .